var myString;
var myNum;
var myBool;
var myVar;
var myVoid;
// let strArr: string[];
// let numArr: number[];
// let boolArr: boolean[];
var strArr;
var numArr;
var boolArr;
var strNumTuple;
myString = "Hello World";
myNum = 22;
myBool = true;
myVar = 5;
strArr = ["Hello", "World"];
numArr = [1, 2, 3];
boolArr = [true, true, true, false, true];
strNumTuple = ["Hello", 7];
// null and undefined are apparently interchangeable
myVoid = null;
var myNull = null;
var myUndefined = undefined;
console.log(myVoid);
